spring:
  application:
    name: spring-boot-resilience4j

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: false

resilience4j:
  ratelimiter:
    instances:
      userDetailsService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
  timelimiter:
    instances:
      userDetailsService:
        timeoutDuration: 2s
        cancelRunningFuture: true
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: "10s"
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      userDetailsService:
        baseConfig: default
  retry:
    instances:
      userDetailsService:
        maxAttempts: 3
        waitDuration: "1s"
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
        eventConsumerBufferSize: 100